# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com

"""
Generate python_pkg.vhd and python_pkg-body.vhd.

The public API consists of the overloads of python_execute and python_call.
The python_call overloads cover all combinations of argument and result
types, which is why they are generated.
"""

from pathlib import Path
from string import Template

SRC_PATH = Path(__file__).parent.parent / "src"

LICENSE = """\
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.
--
-- Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com
--
-- This file is generated by vunit/vhdl/python_bridge/tools/generate_python_pkg.py. Do not edit.
"""

# (VHDL argument type, formal name). None means no argument.
ARGUMENTS = [
    None,
    ("integer", "arg"),
    ("real", "arg"),
    ("boolean", "arg"),
    ("string", "arg"),
    ("std_ulogic", "arg"),
    ("std_ulogic_vector", "arg"),
    ("signed", "arg"),
    ("unsigned", "arg"),
    ("integer_array_t", "arg"),
    ("integer_array_vec_t", "args"),
]

# Result types returned by python_call functions: (VHDL type, value after a mocked failure)
FUNCTION_RESULTS = [
    ("integer", "integer'low"),
    ("real", "0.0"),
    ("boolean", "false"),
    ("string", '""'),
    ("std_ulogic", "'U'"),
    ("std_ulogic_vector", '""'),
    ("integer_array_t", "null_integer_array"),
]

# Result types of python_call procedures, whose width is given by the actual of the result parameter
PROCEDURE_RESULTS = ["std_ulogic_vector", "signed", "unsigned"]


def _profile(argument):
    params = ["function_name : string"]
    if argument is not None:
        params.append(f"{argument[1]} : {argument[0]}")
    return params


def _push(argument):
    if argument is None:
        return ""
    return f" and push_arg(function_name, {argument[1]})"


def generate_spec():
    """
    Generate the package declaration.
    """
    declarations = []
    for result, _ in FUNCTION_RESULTS:
        for argument in ARGUMENTS:
            declarations.append(f"  impure function python_call({'; '.join(_profile(argument))}) return {result};")
        declarations.append("")
    for result in PROCEDURE_RESULTS:
        for argument in ARGUMENTS:
            params = _profile(argument) + [f"result : out {result}"]
            declarations.append(f"  procedure python_call({'; '.join(params)});")
        declarations.append("")

    return Template(
        """\
$license
-- VHDL to Python integration, enabled with add_vhdl_builtins(python=True).
--
-- python_execute executes Python source code or a Python file in a persistent
-- namespace of an embedded Python interpreter. python_call calls a function
-- of that namespace and converts the result to the VHDL type of the context.
-- See the VUnit documentation for the type mappings.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.integer_array_pkg.all;
use work.logger_pkg.all;

package python_pkg is
  -- Logger used to report Python errors, e.g. exceptions with their traceback.
  constant python_logger : logger_t := get_logger("vunit_lib:python");

  -- Execute Python source code (source) or a Python file (file_name). Relative
  -- file names are relative to the directory of the VUnit run script.
  procedure python_execute(source : string := ""; file_name : string := "");

$declarations
end package;
"""
    ).substitute(license=LICENSE, declarations="\n".join(declarations).rstrip("\n"))


def generate_body():
    """
    Generate the package body.
    """
    overloads = []
    for result, failure_value in FUNCTION_RESULTS:
        for argument in ARGUMENTS:
            overloads.append(
                f"""\
  impure function python_call({'; '.join(_profile(argument))}) return {result} is
  begin
    if begin_call(function_name){_push(argument)} and invoke(function_name) then
      return get_result(function_name);
    end if;
    return {failure_value};
  end;
"""
            )
    for result in PROCEDURE_RESULTS:
        for argument in ARGUMENTS:
            params = _profile(argument) + [f"result : out {result}"]
            overloads.append(
                f"""\
  procedure python_call({'; '.join(params)}) is
  begin
    if begin_call(function_name){_push(argument)} and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;
"""
            )

    return Template((Path(__file__).parent / "python_pkg-body.vhd.in").read_text(encoding="utf-8")).substitute(
        license=LICENSE, overloads="\n".join(overloads).rstrip("\n")
    )


def main():
    (SRC_PATH / "python_pkg.vhd").write_text(generate_spec(), encoding="utf-8", newline="\n")
    (SRC_PATH / "python_pkg-body.vhd").write_text(generate_body(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
