-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.
--
-- Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com
--
-- This file is generated by vunit/vhdl/python_bridge/tools/generate_python_pkg.py. Do not edit.

-- VHDL to Python integration, enabled with add_vhdl_builtins(python=True).
--
-- python_execute executes Python source code or a Python file in a persistent
-- namespace of an embedded Python interpreter. python_call calls a function
-- of that namespace and converts the result to the VHDL type of the context.
-- See the VUnit documentation for the type mappings.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.integer_array_pkg.all;
use work.logger_pkg.all;

package python_pkg is
  -- Logger used to report Python errors, e.g. exceptions with their traceback.
  constant python_logger : logger_t := get_logger("vunit_lib:python");

  -- A session is a named Python namespace. Sessions are created on first use
  -- and are isolated from each other, e.g.
  -- constant golden_model : python_session_t := "golden_model";
  type python_session_t is array (positive range <>) of character;
  constant default_session : python_session_t := "default";

  -- Keyword arguments of python_call, created with kw and joined with &, e.g.
  -- python_call("model", input, kwargs => kw("gain", 4) & kw("mode", string'("fast")));
  -- A kw value is transferred to Python when kw is evaluated.
  type python_kwargs_t is array (positive range <>) of character;
  impure function kw(name : string; value : integer) return python_kwargs_t;
  impure function kw(name : string; value : real) return python_kwargs_t;
  impure function kw(name : string; value : boolean) return python_kwargs_t;
  impure function kw(name : string; value : string) return python_kwargs_t;
  impure function kw(name : string; value : std_ulogic) return python_kwargs_t;
  impure function kw(name : string; value : std_ulogic_vector) return python_kwargs_t;
  impure function kw(name : string; value : signed) return python_kwargs_t;
  impure function kw(name : string; value : unsigned) return python_kwargs_t;
  impure function kw(name : string; value : integer_array_t) return python_kwargs_t;

  -- Join lines of Python source code: "a" + "b" is "a" & LF & "b", e.g.
  -- python_execute("def f(x):" + "    return x + 1");
  function "+"(left, right : string) return string;

  -- Execute Python source code (source) or a Python file (file_name). Relative
  -- file names are relative to the directory of the VUnit run script.
  procedure python_execute(source : string := ""; file_name : string := ""; session : python_session_t := default_session);

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer;

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return real;

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return boolean;

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return string;

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic;

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return std_ulogic_vector;

  impure function python_call(function_name : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : integer; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : real; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : boolean; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : string; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : std_ulogic; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; arg : integer_array_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;
  impure function python_call(function_name : string; args : integer_array_vec_t; session : python_session_t := default_session; kwargs : python_kwargs_t := "") return integer_array_t;

  procedure python_call(function_name : string; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : integer; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : real; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : boolean; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : string; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : std_ulogic; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : signed; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : unsigned; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : integer_array_t; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; args : integer_array_vec_t; result : out std_ulogic_vector; session : python_session_t := default_session; kwargs : python_kwargs_t := "");

  procedure python_call(function_name : string; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : integer; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : real; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : boolean; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : string; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : std_ulogic; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : signed; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : unsigned; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : integer_array_t; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; args : integer_array_vec_t; result : out signed; session : python_session_t := default_session; kwargs : python_kwargs_t := "");

  procedure python_call(function_name : string; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : integer; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : real; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : boolean; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : string; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : std_ulogic; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : signed; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : unsigned; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; arg : integer_array_t; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
  procedure python_call(function_name : string; args : integer_array_vec_t; result : out unsigned; session : python_session_t := default_session; kwargs : python_kwargs_t := "");
end package;
