-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.
--
-- Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com
--
-- This file is generated by vunit/vhdl/python_bridge/tools/generate_python_pkg.py. Do not edit.

-- VHDL to Python integration, enabled with add_vhdl_builtins(python=True).
--
-- python_execute executes Python source code or a Python file in a persistent
-- namespace of an embedded Python interpreter. python_call calls a function
-- of that namespace and converts the result to the VHDL type of the context.
-- See the VUnit documentation for the type mappings.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.integer_array_pkg.all;
use work.logger_pkg.all;

package python_pkg is
  -- Logger used to report Python errors, e.g. exceptions with their traceback.
  constant python_logger : logger_t := get_logger("vunit_lib:python");

  -- Execute Python source code (source) or a Python file (file_name). Relative
  -- file names are relative to the directory of the VUnit run script.
  procedure python_execute(source : string := ""; file_name : string := "");

  impure function python_call(function_name : string) return integer;
  impure function python_call(function_name : string; arg : integer) return integer;
  impure function python_call(function_name : string; arg : real) return integer;
  impure function python_call(function_name : string; arg : boolean) return integer;
  impure function python_call(function_name : string; arg : string) return integer;
  impure function python_call(function_name : string; arg : std_ulogic) return integer;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return integer;
  impure function python_call(function_name : string; arg : signed) return integer;
  impure function python_call(function_name : string; arg : unsigned) return integer;
  impure function python_call(function_name : string; arg : integer_array_t) return integer;
  impure function python_call(function_name : string; args : integer_array_vec_t) return integer;

  impure function python_call(function_name : string) return real;
  impure function python_call(function_name : string; arg : integer) return real;
  impure function python_call(function_name : string; arg : real) return real;
  impure function python_call(function_name : string; arg : boolean) return real;
  impure function python_call(function_name : string; arg : string) return real;
  impure function python_call(function_name : string; arg : std_ulogic) return real;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return real;
  impure function python_call(function_name : string; arg : signed) return real;
  impure function python_call(function_name : string; arg : unsigned) return real;
  impure function python_call(function_name : string; arg : integer_array_t) return real;
  impure function python_call(function_name : string; args : integer_array_vec_t) return real;

  impure function python_call(function_name : string) return boolean;
  impure function python_call(function_name : string; arg : integer) return boolean;
  impure function python_call(function_name : string; arg : real) return boolean;
  impure function python_call(function_name : string; arg : boolean) return boolean;
  impure function python_call(function_name : string; arg : string) return boolean;
  impure function python_call(function_name : string; arg : std_ulogic) return boolean;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return boolean;
  impure function python_call(function_name : string; arg : signed) return boolean;
  impure function python_call(function_name : string; arg : unsigned) return boolean;
  impure function python_call(function_name : string; arg : integer_array_t) return boolean;
  impure function python_call(function_name : string; args : integer_array_vec_t) return boolean;

  impure function python_call(function_name : string) return string;
  impure function python_call(function_name : string; arg : integer) return string;
  impure function python_call(function_name : string; arg : real) return string;
  impure function python_call(function_name : string; arg : boolean) return string;
  impure function python_call(function_name : string; arg : string) return string;
  impure function python_call(function_name : string; arg : std_ulogic) return string;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return string;
  impure function python_call(function_name : string; arg : signed) return string;
  impure function python_call(function_name : string; arg : unsigned) return string;
  impure function python_call(function_name : string; arg : integer_array_t) return string;
  impure function python_call(function_name : string; args : integer_array_vec_t) return string;

  impure function python_call(function_name : string) return std_ulogic;
  impure function python_call(function_name : string; arg : integer) return std_ulogic;
  impure function python_call(function_name : string; arg : real) return std_ulogic;
  impure function python_call(function_name : string; arg : boolean) return std_ulogic;
  impure function python_call(function_name : string; arg : string) return std_ulogic;
  impure function python_call(function_name : string; arg : std_ulogic) return std_ulogic;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return std_ulogic;
  impure function python_call(function_name : string; arg : signed) return std_ulogic;
  impure function python_call(function_name : string; arg : unsigned) return std_ulogic;
  impure function python_call(function_name : string; arg : integer_array_t) return std_ulogic;
  impure function python_call(function_name : string; args : integer_array_vec_t) return std_ulogic;

  impure function python_call(function_name : string) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : integer) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : real) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : boolean) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : string) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : std_ulogic) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : signed) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : unsigned) return std_ulogic_vector;
  impure function python_call(function_name : string; arg : integer_array_t) return std_ulogic_vector;
  impure function python_call(function_name : string; args : integer_array_vec_t) return std_ulogic_vector;

  impure function python_call(function_name : string) return integer_array_t;
  impure function python_call(function_name : string; arg : integer) return integer_array_t;
  impure function python_call(function_name : string; arg : real) return integer_array_t;
  impure function python_call(function_name : string; arg : boolean) return integer_array_t;
  impure function python_call(function_name : string; arg : string) return integer_array_t;
  impure function python_call(function_name : string; arg : std_ulogic) return integer_array_t;
  impure function python_call(function_name : string; arg : std_ulogic_vector) return integer_array_t;
  impure function python_call(function_name : string; arg : signed) return integer_array_t;
  impure function python_call(function_name : string; arg : unsigned) return integer_array_t;
  impure function python_call(function_name : string; arg : integer_array_t) return integer_array_t;
  impure function python_call(function_name : string; args : integer_array_vec_t) return integer_array_t;

  procedure python_call(function_name : string; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : integer; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : real; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : boolean; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : string; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : std_ulogic; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : signed; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : unsigned; result : out std_ulogic_vector);
  procedure python_call(function_name : string; arg : integer_array_t; result : out std_ulogic_vector);
  procedure python_call(function_name : string; args : integer_array_vec_t; result : out std_ulogic_vector);

  procedure python_call(function_name : string; result : out signed);
  procedure python_call(function_name : string; arg : integer; result : out signed);
  procedure python_call(function_name : string; arg : real; result : out signed);
  procedure python_call(function_name : string; arg : boolean; result : out signed);
  procedure python_call(function_name : string; arg : string; result : out signed);
  procedure python_call(function_name : string; arg : std_ulogic; result : out signed);
  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out signed);
  procedure python_call(function_name : string; arg : signed; result : out signed);
  procedure python_call(function_name : string; arg : unsigned; result : out signed);
  procedure python_call(function_name : string; arg : integer_array_t; result : out signed);
  procedure python_call(function_name : string; args : integer_array_vec_t; result : out signed);

  procedure python_call(function_name : string; result : out unsigned);
  procedure python_call(function_name : string; arg : integer; result : out unsigned);
  procedure python_call(function_name : string; arg : real; result : out unsigned);
  procedure python_call(function_name : string; arg : boolean; result : out unsigned);
  procedure python_call(function_name : string; arg : string; result : out unsigned);
  procedure python_call(function_name : string; arg : std_ulogic; result : out unsigned);
  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out unsigned);
  procedure python_call(function_name : string; arg : signed; result : out unsigned);
  procedure python_call(function_name : string; arg : unsigned; result : out unsigned);
  procedure python_call(function_name : string; arg : integer_array_t; result : out unsigned);
  procedure python_call(function_name : string; args : integer_array_vec_t; result : out unsigned);
end package;
