-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.
--
-- Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com
--
-- This file is generated by vunit/vhdl/python/tools/generate_python_pkg.py. Do not edit.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.integer_array_pkg.all;
use work.logger_pkg.all;
use work.python_ffi_pkg.all;

package body python_pkg is
  -- Result kinds, must match vunit/python_bridge/native/vunit_python_bridge.c and runtime.py
  constant kind_integer : integer := 0;
  constant kind_real : integer := 1;
  constant kind_boolean : integer := 2;
  constant kind_string : integer := 3;
  constant kind_std_ulogic : integer := 4;
  constant kind_std_ulogic_vector : integer := 5;
  constant kind_signed : integer := 6;
  constant kind_unsigned : integer := 7;
  constant kind_integer_array : integer := 8;

  -- Python represents std_ulogic values by these characters
  constant std_ulogic_characters : string(1 to 9) := "UX01ZWLH-";

  function to_character(value : std_ulogic) return character is
  begin
    return std_ulogic_characters(std_ulogic'pos(value) + 1);
  end;

  function to_std_ulogic(value : character) return std_ulogic is
  begin
    for idx in std_ulogic_characters'range loop
      if std_ulogic_characters(idx) = value then
        return std_ulogic'val(idx - 1);
      end if;
    end loop;
    -- The runtime only returns valid characters
    return 'X';
  end;

  -- Elements from left to right, independent of the range direction
  function logic_image(value : std_ulogic_vector) return string is
    alias normalized : std_ulogic_vector(1 to value'length) is value;
    variable result : string(1 to value'length);
  begin
    for idx in result'range loop
      result(idx) := to_character(normalized(idx));
    end loop;
    return result;
  end;

  function to_logic(value : string) return std_ulogic_vector is
    alias normalized : string(1 to value'length) is value;
    variable result : std_ulogic_vector(value'length - 1 downto 0);
  begin
    for idx in normalized'range loop
      result(value'length - idx) := to_std_ulogic(normalized(idx));
    end loop;
    return result;
  end;

  -----------------------------------------------------------------------------
  -- Transfers through the bridge
  -----------------------------------------------------------------------------
  impure function error_text return string is
    constant length : natural := vpy_error_length;
    variable result : string(1 to length);
    variable chunk : string_chunk_t;
    variable offset, n : natural := 0;
  begin
    while offset < length loop
      n := minimum(chunk_length, length - offset);
      vpy_error_read(chunk, offset, n);
      result(offset + 1 to offset + n) := chunk(1 to n);
      offset := offset + n;
    end loop;
    return result;
  end;

  -- Report a failed operation (status /= 0) with the error from the bridge,
  -- typically a Python traceback. Returns true if the operation succeeded.
  impure function succeeded(status : integer; operation : string) return boolean is
  begin
    if status = 0 then
      return true;
    end if;
    failure(python_logger, operation & " failed:" & LF & error_text);
    return false;
  end;

  impure function send_string(value : string) return integer is
    alias normalized : string(1 to value'length) is value;
    variable chunk : string_chunk_t;
    variable offset, n : natural := 0;
    variable status : integer;
  begin
    status := vpy_buffer_clear;
    while offset < value'length and status = 0 loop
      n := minimum(chunk_length, value'length - offset);
      chunk(1 to n) := normalized(offset + 1 to offset + n);
      status := vpy_buffer_append(chunk, n);
      offset := offset + n;
    end loop;
    return status;
  end;

  impure function result_string return string is
    constant length : natural := vpy_result_meta(0);
    variable result : string(1 to length);
    variable chunk : string_chunk_t;
    variable offset, n : natural := 0;
  begin
    while offset < length loop
      n := minimum(chunk_length, length - offset);
      vpy_result_read_string(chunk, offset, n);
      result(offset + 1 to offset + n) := chunk(1 to n);
      offset := offset + n;
    end loop;
    return result;
  end;

  impure function result_array return integer_array_t is
    constant length : natural := vpy_result_meta(0);
    variable result : integer_array_t := new_3d(
      width => vpy_result_meta(1),
      height => vpy_result_meta(2),
      depth => vpy_result_meta(3),
      bit_width => vpy_result_meta(4),
      is_signed => vpy_result_meta(5) /= 0
    );
    variable chunk : integer_chunk_t;
    variable offset, n : natural := 0;
  begin
    while offset < length loop
      n := minimum(chunk_length, length - offset);
      vpy_result_read_integers(chunk, offset, n);
      for idx in 0 to n - 1 loop
        set(result, offset + idx, chunk(idx));
      end loop;
      offset := offset + n;
    end loop;
    return result;
  end;

  -----------------------------------------------------------------------------
  -- python_execute
  -----------------------------------------------------------------------------
  procedure python_execute(source : string := ""; file_name : string := "") is
    variable ok : boolean;
  begin
    if file_name /= "" then
      if source /= "" then
        failure(python_logger, "python_execute: give either source or file_name, not both");
        return;
      end if;
      ok := succeeded(vpy_begin, "python_execute(file_name => """ & file_name & """)")
            and succeeded(send_string(file_name), "python_execute")
            and succeeded(vpy_execute(1), "python_execute(file_name => """ & file_name & """)");
    else
      ok := succeeded(vpy_begin, "python_execute")
            and succeeded(send_string(source), "python_execute")
            and succeeded(vpy_execute(0), "python_execute");
    end if;
  end;

  -----------------------------------------------------------------------------
  -- python_call building blocks
  -----------------------------------------------------------------------------
  function call_context(function_name : string) return string is
  begin
    return "python_call(""" & function_name & """)";
  end;

  impure function begin_call(function_name : string) return boolean is
  begin
    return succeeded(vpy_begin, call_context(function_name));
  end;

  impure function invoke(function_name : string) return boolean is
  begin
    return succeeded(send_string(function_name), call_context(function_name))
      and succeeded(vpy_call, call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : integer) return boolean is
  begin
    return succeeded(vpy_push_integer(arg), call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : real) return boolean is
  begin
    return succeeded(vpy_push_real(arg), call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : boolean) return boolean is
  begin
    return succeeded(vpy_push_boolean(boolean'pos(arg)), call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : string) return boolean is
  begin
    return succeeded(send_string(arg), call_context(function_name))
      and succeeded(vpy_push_string, call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : std_ulogic) return boolean is
  begin
    return push_arg(function_name, string'(1 => to_character(arg)));
  end;

  impure function push_arg(function_name : string; arg : std_ulogic_vector) return boolean is
  begin
    return push_arg(function_name, logic_image(arg));
  end;

  impure function push_arg(function_name : string; arg : signed) return boolean is
  begin
    return succeeded(send_string(logic_image(std_ulogic_vector(arg))), call_context(function_name))
      and succeeded(vpy_push_bits(1), call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : unsigned) return boolean is
  begin
    return succeeded(send_string(logic_image(std_ulogic_vector(arg))), call_context(function_name))
      and succeeded(vpy_push_bits(0), call_context(function_name));
  end;

  impure function push_arg(function_name : string; arg : integer_array_t) return boolean is
    constant length : natural := work.integer_array_pkg.length(arg);
    variable chunk : integer_chunk_t;
    variable offset, n : natural := 0;
  begin
    if not succeeded(
      vpy_push_array(length, width(arg), height(arg), depth(arg), bit_width(arg), boolean'pos(is_signed(arg))),
      call_context(function_name)
    ) then
      return false;
    end if;

    while offset < length loop
      n := minimum(chunk_length, length - offset);
      for idx in 0 to n - 1 loop
        chunk(idx) := get(arg, offset + idx);
      end loop;
      if not succeeded(vpy_array_write(chunk, n), call_context(function_name)) then
        return false;
      end if;
      offset := offset + n;
    end loop;
    return true;
  end;

  impure function push_arg(function_name : string; args : integer_array_vec_t) return boolean is
  begin
    for idx in args'range loop
      if not push_arg(function_name, args(idx)) then
        return false;
      end if;
    end loop;
    return true;
  end;

  impure function convert_result(function_name : string; kind : integer; width : integer := -1) return boolean is
  begin
    return succeeded(vpy_result(kind, width), call_context(function_name));
  end;

  impure function get_result(function_name : string) return integer is
  begin
    if convert_result(function_name, kind_integer) then
      return vpy_result_integer;
    end if;
    return integer'low;
  end;

  impure function get_result(function_name : string) return real is
  begin
    if convert_result(function_name, kind_real) then
      return vpy_result_real;
    end if;
    return 0.0;
  end;

  impure function get_result(function_name : string) return boolean is
  begin
    if convert_result(function_name, kind_boolean) then
      return vpy_result_integer /= 0;
    end if;
    return false;
  end;

  impure function get_result(function_name : string) return string is
  begin
    if convert_result(function_name, kind_string) then
      return result_string;
    end if;
    return "";
  end;

  impure function get_result(function_name : string) return std_ulogic is
  begin
    if convert_result(function_name, kind_std_ulogic) then
      return to_logic(result_string)(0);
    end if;
    return 'U';
  end;

  impure function get_result(function_name : string) return std_ulogic_vector is
  begin
    if convert_result(function_name, kind_std_ulogic_vector) then
      return to_logic(result_string);
    end if;
    return "";
  end;

  impure function get_result(function_name : string) return integer_array_t is
  begin
    if convert_result(function_name, kind_integer_array) then
      return result_array;
    end if;
    return null_integer_array;
  end;

  procedure get_result(function_name : string; result : out std_ulogic_vector) is
  begin
    if convert_result(function_name, kind_std_ulogic_vector, result'length) then
      result := to_logic(result_string);
    end if;
  end;

  procedure get_result(function_name : string; result : out signed) is
  begin
    if convert_result(function_name, kind_signed, result'length) then
      result := signed(to_logic(result_string));
    end if;
  end;

  procedure get_result(function_name : string; result : out unsigned) is
  begin
    if convert_result(function_name, kind_unsigned, result'length) then
      result := unsigned(to_logic(result_string));
    end if;
  end;

  -----------------------------------------------------------------------------
  -- python_call
  -----------------------------------------------------------------------------
  impure function python_call(function_name : string) return integer is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : integer) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : real) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : boolean) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : string) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : signed) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : unsigned) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return integer is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return integer'low;
  end;

  impure function python_call(function_name : string) return real is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : integer) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : real) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : boolean) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : string) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : signed) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : unsigned) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return real is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 0.0;
  end;

  impure function python_call(function_name : string) return boolean is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : integer) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : real) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : boolean) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : string) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : signed) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : unsigned) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return boolean is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return false;
  end;

  impure function python_call(function_name : string) return string is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : integer) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : real) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : boolean) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : string) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : signed) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : unsigned) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return string is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string) return std_ulogic is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : integer) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : real) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : boolean) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : string) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : signed) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : unsigned) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return std_ulogic is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return 'U';
  end;

  impure function python_call(function_name : string) return std_ulogic_vector is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : integer) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : real) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : boolean) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : string) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : signed) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : unsigned) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return std_ulogic_vector is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return "";
  end;

  impure function python_call(function_name : string) return integer_array_t is
  begin
    if begin_call(function_name) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : integer) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : real) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : boolean) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : string) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : std_ulogic) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : std_ulogic_vector) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : signed) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : unsigned) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; arg : integer_array_t) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  impure function python_call(function_name : string; args : integer_array_vec_t) return integer_array_t is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      return get_result(function_name);
    end if;
    return null_integer_array;
  end;

  procedure python_call(function_name : string; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : integer; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : real; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : boolean; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : string; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : std_ulogic; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : signed; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : unsigned; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : integer_array_t; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; args : integer_array_vec_t; result : out std_ulogic_vector) is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; result : out signed) is
  begin
    if begin_call(function_name) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : integer; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : real; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : boolean; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : string; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : std_ulogic; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : signed; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : unsigned; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : integer_array_t; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; args : integer_array_vec_t; result : out signed) is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; result : out unsigned) is
  begin
    if begin_call(function_name) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : integer; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : real; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : boolean; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : string; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : std_ulogic; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : std_ulogic_vector; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : signed; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : unsigned; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; arg : integer_array_t; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, arg) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;

  procedure python_call(function_name : string; args : integer_array_vec_t; result : out unsigned) is
  begin
    if begin_call(function_name) and push_arg(function_name, args) and invoke(function_name) then
      get_result(function_name, result);
    end if;
  end;
end package body;
