-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.
--
-- Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com
--
-- This file is generated by vunit/vhdl/python/tools/generate_python_pkg.py. Do not edit.
--
-- VUnit extensions of the Python API, available for the simulators using the
-- VUnit Python bridge (NVC and GHDL). Make them visible with
--
--   use vunit_lib.python_ext_pkg.all;
--
-- in addition to context vunit_lib.python_context.
--
-- Like the operations of python_pkg, every operation takes the session it is
-- performed in as its last parameter, defaulting to the default session.
--
-- Note that the additional arg overloads make string literals ambiguous:
-- arg("hello") can be a string, a std_ulogic_vector, a signed or an unsigned
-- value and needs a qualified expression such as arg(string'("hello")).
-- std_ulogic_vector results are only available under their explicit names
-- (eval_std_ulogic_vector, call_std_ulogic_vector), not as eval/call
-- overloads, which keeps check_equal(eval("17"), 17) unambiguous.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.integer_array_pkg.all;
use work.integer_vector_ptr_pkg.all;
use work.python_ffi_pkg.all;
use work.python_pkg.all;

package python_ext_pkg is
  -----------------------------------------------------------------------------
  -- Additional argument values of call
  -----------------------------------------------------------------------------
  -- std_ulogic and std_ulogic_vector values become Python strings of the
  -- characters "UX01ZWLH-", signed and unsigned values become Python ints and
  -- real_vector and integer_vector_ptr_t values become Python lists. An
  -- integer_array_t value is transferred to Python and referred to by the
  -- expression, which means that it can be used in several calls.
  function arg(value : std_ulogic) return arg_t;
  function kwarg(kw : string; value : std_ulogic) return arg_t;
  function arg(value : std_ulogic_vector) return arg_t;
  function kwarg(kw : string; value : std_ulogic_vector) return arg_t;
  impure function arg(value : signed) return arg_t;
  impure function kwarg(kw : string; value : signed) return arg_t;
  impure function arg(value : unsigned) return arg_t;
  impure function kwarg(kw : string; value : unsigned) return arg_t;
  function arg(value : real_vector) return arg_t;
  function kwarg(kw : string; value : real_vector) return arg_t;
  impure function arg(value : integer_vector_ptr_t) return arg_t;
  impure function kwarg(kw : string; value : integer_vector_ptr_t) return arg_t;
  impure function arg(value : integer_array_t) return arg_t;
  impure function kwarg(kw : string; value : integer_array_t) return arg_t;

  -----------------------------------------------------------------------------
  -- Additional result types of eval
  -----------------------------------------------------------------------------
  impure function eval_boolean(
    expr : string; session : python_session_t := default_session
  ) return boolean;
  alias eval is eval_boolean[string, python_session_t return boolean];

  impure function eval_std_ulogic(
    expr : string; session : python_session_t := default_session
  ) return std_ulogic;
  alias eval is eval_std_ulogic[string, python_session_t return std_ulogic];

  impure function eval_std_ulogic_vector(
    expr : string; session : python_session_t := default_session
  ) return std_ulogic_vector;

  impure function eval_integer_array(
    expr : string; session : python_session_t := default_session
  ) return integer_array_t;
  alias eval is eval_integer_array[string, python_session_t return integer_array_t];

  procedure eval_std_ulogic_vector(
    expr : string; result : out std_ulogic_vector; session : python_session_t := default_session
  );
  procedure eval_signed(
    expr : string; result : out signed; session : python_session_t := default_session
  );
  procedure eval_unsigned(
    expr : string; result : out unsigned; session : python_session_t := default_session
  );

  -----------------------------------------------------------------------------
  -- Additional result types of call
  -----------------------------------------------------------------------------
  impure function call_real_vector(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return real_vector;
  alias call is call_real_vector[
    string, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, python_session_t return real_vector];

  impure function call_string(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return string;
  alias call is call_string[
    string, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, python_session_t return string];

  impure function call_integer_vector_ptr(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return integer_vector_ptr_t;
  alias call is call_integer_vector_ptr[
    string, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, python_session_t return integer_vector_ptr_t];

  impure function call_boolean(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return boolean;
  alias call is call_boolean[
    string, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, python_session_t return boolean];

  impure function call_std_ulogic(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return std_ulogic;
  alias call is call_std_ulogic[
    string, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, python_session_t return std_ulogic];

  impure function call_std_ulogic_vector(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return std_ulogic_vector;

  impure function call_integer_array(
    identifier : string; arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  ) return integer_array_t;
  alias call is call_integer_array[
    string, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, arg_t, python_session_t return integer_array_t];

  procedure call_std_ulogic_vector(
    identifier : string; result : out std_ulogic_vector;
    arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  );
  procedure call_signed(
    identifier : string; result : out signed;
    arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  );
  procedure call_unsigned(
    identifier : string; result : out unsigned;
    arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 : arg_t := null_arg;
    session : python_session_t := default_session
  );

  -----------------------------------------------------------------------------
  -- Execution of Python files
  -----------------------------------------------------------------------------
  -- Execute a Python file. A relative file name is relative to the directory
  -- of the run script. The file is executed with __file__ set and its own
  -- directory on sys.path so that it can import its siblings.
  procedure exec_file(file_name : string; session : python_session_t := default_session);
end package;
