# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com

"""
Generate python_pkg.vhd and python_pkg-body.vhd.

The public API consists of the overloads of python_execute and python_call.
The python_call overloads cover all combinations of argument and result
types, which is why they are generated.
"""

from pathlib import Path
from string import Template

SRC_PATH = Path(__file__).parent.parent / "src"

LICENSE = """\
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this file,
-- You can obtain one at http://mozilla.org/MPL/2.0/.
--
-- Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com
--
-- This file is generated by vunit/vhdl/python_bridge/tools/generate_python_pkg.py. Do not edit.
"""

# (VHDL argument type, formal name). None means no argument.
ARGUMENTS = [
    None,
    ("integer", "arg"),
    ("real", "arg"),
    ("boolean", "arg"),
    ("string", "arg"),
    ("std_ulogic", "arg"),
    ("std_ulogic_vector", "arg"),
    ("signed", "arg"),
    ("unsigned", "arg"),
    ("integer_array_t", "arg"),
    ("integer_array_vec_t", "args"),
]

# Result types returned by python_call functions: (VHDL type, value after a mocked failure)
FUNCTION_RESULTS = [
    ("integer", "integer'low"),
    ("real", "0.0"),
    ("boolean", "false"),
    ("string", '""'),
    ("std_ulogic", "'U'"),
    ("std_ulogic_vector", '""'),
    ("integer_array_t", "null_integer_array"),
]

# Result types of python_call procedures, whose width is given by the actual of the result parameter
PROCEDURE_RESULTS = ["std_ulogic_vector", "signed", "unsigned"]


# Parameters as (name, type, default) like the VHDL declarations they become
SESSION = ("session", "python_session_t", "default_session")
KWARGS = ("kwargs", "python_kwargs_t", '""')

# Types of keyword argument values created with kw()
KEYWORD_VALUES = [
    "integer",
    "real",
    "boolean",
    "string",
    "std_ulogic",
    "std_ulogic_vector",
    "signed",
    "unsigned",
    "integer_array_t",
]


def _profile(argument):
    params = [("function_name", "string", None)]
    if argument is not None:
        params.append((argument[1], argument[0], None))
    return params


def _declaration(subprogram, params, suffix):
    """
    A declaration with one parameter per line and aligned types and defaults,
    like the other generated VUnit packages.
    """
    name_width = max(len(name) for name, _, _ in params)
    type_width = max(len(type_name) for _, type_name, default in params if default is not None)
    lines = [f"  {subprogram}("]
    for index, (name, type_name, default) in enumerate(params):
        value = "" if default is None else f"{type_name.ljust(type_width)} := {default}"
        terminator = ";" if index < len(params) - 1 else f"){suffix}"
        lines.append(f"    {name.ljust(name_width)} : {value or type_name}{terminator}")
    return "\n".join(lines)


def _push(argument):
    if argument is None:
        return ""
    return f" and push_arg(call_context(function_name, session), {argument[1]})"


def generate_spec():
    """
    Generate the package declaration.
    """
    declarations = []
    for result, _ in FUNCTION_RESULTS:
        for argument in ARGUMENTS:
            params = _profile(argument) + [SESSION, KWARGS]
            declarations.append(_declaration("impure function python_call", params, f" return {result};"))
        declarations.append("")
    for result in PROCEDURE_RESULTS:
        for argument in ARGUMENTS:
            params = _profile(argument) + [("result", f"out {result}", None), SESSION, KWARGS]
            declarations.append(_declaration("procedure python_call", params, ";"))
        declarations.append("")

    return Template(
        """\
$license
-- VHDL to Python integration, enabled with add_vhdl_builtins(python=True).
--
-- python_execute executes Python source code or a Python file in a persistent
-- namespace of an embedded Python interpreter. python_call calls a function
-- of that namespace and converts the result to the VHDL type of the context.
-- See the VUnit documentation for the type mappings.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.integer_array_pkg.all;
use work.logger_pkg.all;

package python_pkg is
  -- Logger used to report Python errors, e.g. exceptions with their traceback.
  constant python_logger : logger_t := get_logger("vunit_lib:python");

  -- A session is a named Python namespace. Sessions are created on first use
  -- and are isolated from each other, e.g.
  -- constant golden_model : python_session_t := "golden_model";
  type python_session_t is array (positive range <>) of character;
  constant default_session : python_session_t := "default";

  -- Keyword arguments of python_call, created with kw and joined with &, e.g.
  -- python_call("model", input, kwargs => kw("gain", 4) & kw("mode", string'("fast")));
  -- A kw value is transferred to Python when kw is evaluated.
  type python_kwargs_t is array (positive range <>) of character;
$keyword_declarations

  -- Join lines of Python source code: "a" + "b" is "a" & LF & "b", e.g.
  -- python_execute("def f(x):" + "    return x + 1");
  function "+"(left, right : string) return string;

  -- Execute Python source code (source) or a Python file (file_name). Relative
  -- file names are relative to the directory of the VUnit run script.
  procedure python_execute(
    source    : string           := "";
    file_name : string           := "";
    session   : python_session_t := default_session);

$declarations
end package;
"""
    ).substitute(
        license=LICENSE,
        declarations="\n".join(declarations).rstrip("\n"),
        keyword_declarations="\n".join(
            f"  impure function kw(name : string; value : {value}) return python_kwargs_t;" for value in KEYWORD_VALUES
        ),
    )


def generate_body():
    """
    Generate the package body.
    """
    overloads = []
    for result, failure_value in FUNCTION_RESULTS:
        for argument in ARGUMENTS:
            params = _profile(argument) + [SESSION, KWARGS]
            overloads.append(
                f"""\
{_declaration("impure function python_call", params, f" return {result} is")}
  begin
    if begin_call(function_name, session){_push(argument)}
      and push_kwargs(function_name, session, kwargs) and invoke(function_name, session) then
      return get_result(function_name, session);
    end if;
    return {failure_value};
  end;
"""
            )
    for result in PROCEDURE_RESULTS:
        for argument in ARGUMENTS:
            params = _profile(argument) + [("result", f"out {result}", None), SESSION, KWARGS]
            overloads.append(
                f"""\
{_declaration("procedure python_call", params, " is")}
  begin
    if begin_call(function_name, session){_push(argument)}
      and push_kwargs(function_name, session, kwargs) and invoke(function_name, session) then
      get_result(function_name, session, result);
    end if;
  end;
"""
            )

    return Template((Path(__file__).parent / "python_pkg-body.vhd.in").read_text(encoding="utf-8")).substitute(
        license=LICENSE,
        overloads="\n".join(overloads).rstrip("\n"),
        keyword_functions="\n".join(
            f"""\
  impure function kw(name : string; value : {value}) return python_kwargs_t is
  begin
    if begin_operation(default_session, kw_context(name)) and push_arg(kw_context(name), value) then
      return stage_keyword(name);
    end if;
    return "";
  end;
"""
            for value in KEYWORD_VALUES
        ).rstrip("\n"),
    )


def main():
    (SRC_PATH / "python_pkg.vhd").write_text(generate_spec(), encoding="utf-8", newline="\n")
    (SRC_PATH / "python_pkg-body.vhd").write_text(generate_body(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
